config/routes.rb
ISCCLims::Application.routes.draw do
  
  root :to => 'welcome#index'
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :sessions
  resources :auth_users
  resources :users
  match 'forgot' => 'users#forgot', :as => :forgot
  match 'activate/:activation_code' => 'users#activate', :as => :activate
  match 'reset/:reset_code' => 'users#reset', :as => :reset

  get 'samples/autocomplete_sample_strain'  
  get 'samples/autocomplete_sample_intestinal_sc_marker'
  get 'samples/autocomplete_sample_sc_marker_validation_method'
  resources :samples do
    collection do
      get :shipment_confirm
      get :sample_ship
    end    
  end
  
  match 'list_intransit' => 'samples#list_intransit', :as => :recv_samples
  match 'show_sop' => 'samples#show_sop', :as => :show_sop
  match 'sample_results' => 'samples#show_results', :as => :sample_results
  
  resources :result_files
  match 'show_rdef' => 'result_files#show_rdef', :as => :show_rdef
  match 'choose_lab' => 'result_files#choose_lab', :as => :choose_lab
  match 'edit_multi' => 'result_files#edit_multi', :as => :edit_multi
  match 'update_multi' => 'result_files#update_multi', :as => :update_multi
  match 'destroy' => 'result_files#destroy', :as => :destroy
  match '/:controller(/:action(/:id))'
  

end

app/models/sample.rb
# == Schema Information
#
# Table name: samples
#
#  id                           :integer(4)      not null, primary key
#  barcode_key                  :string(8)       default(""), not null
#  sample_name                  :string(25)
#  sample_date                  :date
#  organism                     :string(20)
#  strain                       :string(15)
#  sex                          :string(6)
#  age_in_weeks                 :string(2)
#  intestinal_region            :string(50)
#  intestinal_region_definition :string(255)
#  intestinal_sc_marker         :string(50)
#  isolation_protocol_id        :integer(4)
#  facs_protocol_id             :integer(4)
#  facs_protocol                :string(100)
#  sc_marker_validation_method  :string(50)
#  secondary_validation_results :string(255)
#  molecule_type                :string(10)
#  number_of_cells              :integer(4)
#  comments                     :string(255)
#  lab_id                       :integer(4)      not null
#  updated_by                   :integer(4)
#  created_at                   :datetime
#  updated_at                   :timestamp       not null
#

class Sample < ActiveRecord::Base
  belongs_to :lab
  has_one :shipment
  has_and_belongs_to_many :result_files
  
  accepts_nested_attributes_for :shipment, :allow_destroy => true
  
  validates_presence_of :barcode_key, :sample_name, :sample_date, :organism, :strain, :age_in_weeks,
                        :intestinal_region
  
  validates_numericality_of :age_in_weeks, :only_integer => true, :message => "must be an integer"
  #validates_inclusion_of :age_in_weeks, :in => 6..10, :message => "must be between 6 and 10"
  
  before_validation :set_barcode, :on => :create
  
  scope :userlab, lambda{|user| {:conditions => (user.has_consortium_access? ? nil : ["samples.lab_id = ?", user.lab_id])}}
  
  SEX = ['Male', 'Female']
  SC_MARKERS = ['Lgr5 hi', 'Lgr5 lo', 'Bmi1', 'SP hi', 'SP lo', 'label-retaining', 'CD166',
                'CD24', 'p-beta-catS552', 'Mus-1', 'DCAMKL']
  MARKER_VALIDATION = ['none', 'qPCR', 'clonogenic culture', '2nd FACS sort'] 
  
  SAMPLE_DEFAULT = {:sample_date => Date.today,
                    :organism => 'Mus musculus',
                    :sex => 'Male',
                    :age_in_weeks => 6}
  MIN_CELLS = 3000
  
  SAMPLE_SOP_PATH = File.join(Rails.root, 'public', 'files', 'Sample_Shipping_SOP.doc')
  
  def barcode_and_name
    [barcode_key,sample_name].join('/')
  end
  
  def set_barcode
    self.barcode_key = "%03d" % Barcode.next_barcode
  end
  
  def cells_lt_min
    (number_of_cells.nil? ? true : (number_of_cells < MIN_CELLS ? true : false))
  end
  
  def self.find_and_group_by_lab(user, condition_array=nil)
    samples = self.userlab(user).includes(:shipment, :lab).order('lab_id, barcode_key').where(sql_where(condition_array)).all
    return samples.group_by {|sample| sample.lab.lab_name}
  end
  
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  load_and_authorize_resource
  
  autocomplete :sample, :strain
  autocomplete :sample, :intestinal_sc_marker
  autocomplete :sample, :sc_marker_validation_method
  
  # GET /samples
  def index
    @samples = Sample.find_and_group_by_lab(current_user)
  end
  
  def list_intransit
    @samples = Sample.userlab(current_user).includes(:shipment).where('shipments.date_received IS NULL').all
  end

  # GET /samples/1
  def show
    @sample = Sample.includes(:shipment).find(params[:id])
  end
  
  def show_sop
    headers["Content-Type"] = "application/msword"
    send_file("#{Sample::SAMPLE_SOP_PATH}") 
  end

  # GET /samples/new
  def new
    @sample = Sample.new(Sample::SAMPLE_DEFAULT)
  end
  
  def shipment_confirm
    @sample = Sample.includes(:shipment).find(params[:id])
    if !@sample.shipment
      checkbox_flags = {:confirm_nr_cells => (@sample.cells_lt_min ? 'N' : 'Y')}
      @sample.build_shipment(Shipment::SHIPMENT_DEFAULT.merge!checkbox_flags)
    end
  end
  
  def sample_ship
    @sample = Sample.includes(:shipment).find(params[:id])
    if !@sample.shipment
      checkbox_flags = {:confirm_nr_cells => (@sample.cells_lt_min ? 'N' : 'Y')}
      @sample.build_shipment(Shipment::SHIPMENT_DEFAULT.merge!checkbox_flags)
    end
  end
  
#  def ship_dtls
#    @sample = Sample.find(params[:id])
#    render :update do |page|
#      page.replace_html 'shipment', :partial => 'shipment_form', :locals => {:sample => @sample}
#    end
#  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.includes(:shipment).find(params[:id])
  end

  # POST /samples
  def create
    @sample = Sample.new(params[:sample].merge!(:lab_id => current_user.lab_id))
    if @sample.save
      redirect_to :action => :shipment_confirm, :id => @sample.id
    else
      render :action => "new"
    end
  end

  # PUT /samples/1
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to(@sample, :notice => 'Sample was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sample.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # TODO
  # crack open attributes to see what it is gathering
  # it appears from the debug that the shipping id is getting written to the shipment table, 
  # but not the date_received
  def update_multi
    params[:sample].each do |id, attributes|
      sample = Sample.find(id)
      sample.update_attributes(attributes) 
    end
    flash[:notice] = 'Sample receipt updated'
    redirect_to samples_path
    
  end

  # DELETE /samples/1
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy
    redirect_to(samples_url)
  end
  
  def upd_date_recvd
    new_date = (params[:checked_value] == '1' ? Date.today : nil)
    render :update do |page|
      page['sample_' + params[:id] + '_shipment_attributes_date_received'].value = new_date
    end
  end
  
  #def auto_complete_for_strain
  def autocomplete_sample_strain
    @svalues = Sample.select('distinct strain').where('strain LIKE ?', params[:term] + '%').all
    #render :inline => "<%= auto_complete_result(@svalues, 'strain') %>"
    list = @svalues.map {|sv| Hash[ id: sv.id, label: sv.strain, name: sv.strain]}
    render json: list
  end
  
  def autocomplete_sample_intestinal_sc_marker
    @svalues = Sample.select('distinct intestinal_sc_marker').where('intestinal_sc_marker LIKE ?', params[:term] + '%').all
    Sample::SC_MARKERS.each do |marker|
      @svalues.push(Sample.new(:intestinal_sc_marker => marker)) if marker[0..(params[:term].length-1)] == params[:term]
    end
    #render :inline => "<%= auto_complete_result(@svalues, 'intestinal_sc_marker') %>"
    list = @svalues.map {|im| Hash[ id: im.id, label: im.intestinal_sc_marker, name: im.intestinal_sc_marker]}
    render json: list
  end
  
  def autocomplete_sample_sc_marker_validation_method
    @svalues = Sample.select('distinct sc_marker_validation_method').where('sc_marker_validation_method LIKE ?', params[:term] + '%').all
    Sample::MARKER_VALIDATION.each do |validation|
      @svalues.push(Sample.new(:sc_marker_validation_method => validation)) if validation[0..(params[:term].length-1)] == params[:term]
    end
    @svalues = @svalues.uniq { |h| h[:sc_marker_validation_method] }
    #render :inline => "<%= auto_complete_result(@svalues, 'sc_marker_validation_method') %>"
    list = @svalues.map {|mvm| Hash[ id: mvm.id, label: mvm.sc_marker_validation_method, name: mvm.sc_marker_validation_method]}
    render json: list
  end
 
end

app/helpers/samples_helper.rb
module SamplesHelper
  def ship_weekday(date_shipped, int_or_string='string')
    if int_or_string == 'int'
      return (date_shipped.nil? ? -1 : date_shipped.strftime("%w"))
    else
      return (date_shipped.nil? ? '' : date_shipped.strftime("%A"))
    end
  end
end

app/views/samples/_sample_form.html.erb
<fieldset class="form">
<legend>Sample Details</legend>
<table class="form">
	<tr>
	  <th><%=f.label :sample_name %>:</th><td><%=f.text_field(:sample_name, :size => 25) %></td>
	  <th><%=f.label :sample_date %>:</th>
	  <td><!--%=f.calendar_date_select(:sample_date, :size => 10, :valid_date_check => "date <= (new Date()).stripTime()") %-->
      <%=f.datepicker 'sample_date', dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true, size: 10 %>
	  </td>
	</tr>
	<tr>
	  <th><%=f.label :organism %>:</th><td><%=f.text_field(:organism, :size => 25) %></td>
	  <th><%=f.label :strain %>:</th> 
	  <td><!--%=f.text_field_with_auto_complete(:strain, {},
             {:url => {:controller => :samples, :action => :auto_complete_for_strain},
              :param_name => :search, :min_chars => 2, :method => :get})%-->
          <%=f.autocomplete_field :strain, samples_autocomplete_sample_strain_path %></td>
    </tr>
    <tr>
	  <th><%=f.label :sex %>:</th><td><%=f.select(:sex, Sample::SEX) %></td>
	  <th><%=f.label :age_in_weeks, 'Age (in weeks)' %>:</th><td><%=f.text_field(:age_in_weeks, :size => 4) %></td>
    </tr>
	<tr>
	  <th><%=f.label :intestinal_region %>:</th><td><%=f.text_field(:intestinal_region, :size => 15) %></td>
	  <th><%=f.label :intestinal_region_definition %>:</th><td><%=f.text_field(:intestinal_region_definition, :size => 15) %></td>
    </tr>
	<tr>
	  <th><%=f.label :intestinal_sc_marker, 'Intestinal SC marker' %>:</th> 
	  <td><!--%=f.text_field_with_auto_complete(:intestinal_sc_marker, {},
             {:url => {:controller => :samples, :action => :auto_complete_for_intestinal_sc_marker},
              :param_name => :search, :min_chars => 2, :method => :get})%-->
          <%=f.autocomplete_field :intestinal_sc_marker, samples_autocomplete_sample_intestinal_sc_marker_path %>
      </td>
	</tr>	
	<tr>
	  <th><%=f.label :number_of_cells, 'No of cells' %>:</th><td><%=f.text_field(:number_of_cells, :size => 10) %></td>
	  <th><%=f.label :facs_protocol, 'FACS protocol' %>:</th><td><%=f.text_field(:facs_protocol) %></td>
    </tr>
	<tr>
	  <th><%=f.label :sc_marker_validation_method, 'SC marker validation method' %>:</th>
	  <td><!--%=f.text_field_with_auto_complete(:sc_marker_validation_method, {},
             {:url => {:controller => :samples, :action => :auto_complete_for_sc_marker_validation_method},
              :param_name => :search, :min_chars => 2, :method => :get})%-->
           <%=f.autocomplete_field :sc_marker_validation_method, samples_autocomplete_sample_sc_marker_validation_method_path %>
      </td>
	  <th><%=f.label :secondary_validation_results %>:</th><td><%=f.text_field(:secondary_validation_results) %></td>
	</tr>	
    <tr>
      <th>Comments:</th>
      <td colspan=3><%=f.text_area :comments, :cols => 55, :rows => 2 %></td>
    </tr>
</table>
</fieldset>

app/views/samples/_sample_show.html.erb
<fieldset class="info">
<legend>Sample Details</legend>
<table class="info">
    <tr>
      <th>Barcode:</th><td colspan="3"><%=h sample.barcode_key %></td>
	</tr>
	<tr>
      <th>Sample Name:</th><td><%=h sample.sample_name %></td>
	  <th>Sample Date:</th><td><%=h sample.sample_date %></td>
	</tr>	
    <tr>
      <th>Organism:</th><td><%=h sample.organism %></td>    
      <th>Strain:</th><td><%=h sample.strain %></td>
    </tr>
    <tr> 
	  <th>Sex:</th><td><%=h sample.sex %></td>
	  <th>Age(in weeks):</th><td><%=h sample.age_in_weeks %></td> 
	</tr>
	<tr>
	  <th>Intestinal region:</th><td><%=h sample.intestinal_region %></td>
      <th>Intestinal region definition:</th><td><%=h sample.intestinal_region_definition %></td>
    </tr>
    <tr>
	  <th>Intestinal SC marker:</th><td colspan="3"><%=h sample.intestinal_sc_marker %></td>
	</tr>	
	<tr>
	  <th>Number of cells:</th><td><%=h sample.number_of_cells %></td>
      <th>FACS protocol:</th><td><%=h sample.facs_protocol_id %></td>
    </tr>
    <tr>	  
	  <th>SC marker validation method:</th><td><%=h sample.sc_marker_validation_method %></td>
	  <th>SC validation results:</th><td><%=h sample.secondary_validation_results %></td>
    </tr>
    <tr>
      <th>Comments:</th><td colspan=3><%=h sample.comments %></td>
    </tr>
</table>
</fieldset>
<%= raw break_clear %>

app/views/samples/_shipment_checklist.html.erb
<fieldset class="form">
<legend>Please verify the following items prior to shipping</legend>
<table class="form">
  <tr>
  	<td><%=f.check_box(:confirm_barcode, {}, 'Y', 'N')%>Sample labeled with barcode: <%=h sample.barcode_key %></td>
	<td width="25"></td>
	<td rowspan="4"><u>Ship samples to:</u><br/>
	Julie Wilhelmy<br/>
	Stanford Genome Technology Center<br/>
	855 S.California Ave<br/>
	Palo Alto, CA 94304<br/>
	</td>
  </tr>  
  <tr>
  	<td <%='class="dkred"' if sample.cells_lt_min %>><%=f.check_box(:confirm_nr_cells, {}, 'Y', 'N')%>
      Number of cells > <%=h Sample::MIN_CELLS %>, or confirmed ok with Julie</td>
	<td></td>
  </tr> 
  <tr>
  	<td><%=f.check_box(:confirm_ship_day, {}, 'Y', 'N')%>Shipment day is before Thursday,
    or confirmed ok with Julie</td>
    <td></td>
  </tr>
  <tr>
  	<td><%=f.check_box(:confirm_dry_ice, {}, 'Y', 'N')%>Container 75% full of dry ice</td>
	<td></td>
  </tr>
  <tr>
  	<td><%=f.check_box(:confirm_fedex_nr, {}, 'Y', 'N')%>FedEx number entered correctly</td>
	<td></td>
  </tr>
  <tr>
  	<td><%=f.check_box(:confirm_ship_email, {}, 'Y', 'N')%>Emailed Julie with shipment details</td>
	<td colspan=2></td>
  </tr>  
</table>
</fieldset>

app/views/samples/_shipment_form.html.erb
<fieldset class="form">
<legend>Shipment Details</legend>
<table class="form">	
    <tr>
      <th><%=f.label :date_shipped, 'Ship Date' %>:</th>
	  <td><!--%=f.calendar_date_select(:date_shipped, :size => 15, :valid_date_check => "date <= (new Date()).stripTime()") %-->
      <%=f.datepicker 'date_shipped', dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true, minDate: "-1y", maxDate: "0", size: 15 %>
	  </td>
	  <th><%=f.label :fedex_tracking_nr, 'FedEx tracking number' %>:</th>
	  <td><%=f.text_field(:fedex_tracking_nr, :size => 30) %></td>
	</tr>
	
	<% if !f.object.new_record? && current_user.has_admin_access? %>
	<tr>
	  <th><%=f.label :date_received %>:</th>
      <td><!--%=f.calendar_date_select(:date_received, :size => 15, :valid_date_check => "date <= (new Date()).stripTime()") %-->
      <%=f.datepicker 'date_received', dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true, minDate: "-1y", maxDate: "0", size: 15 %>
      </td>
	  <td colspan=2></td>
	</tr>
	<% end %>
	
    <tr>
      <th>Comments:</th>
      <td colspan="3"><%=f.text_area :comments, :cols => 45, :rows => 2 %></td>
    </tr>
</table>
</fieldset>
<%= render :partial => 'shipment_checklist', :locals => {:f => f, :sample => sample} %>

app/views/samples/_shipment_show.html.erb
<fieldset class="info">
<legend>Shipment Details</legend>
<table class="info">
  <tr>
    <th>Date Shipped:</th><td><%=h shipment.date_shipped %></td>
    <th>Date Received:</th><td><%=h shipment.date_received_or_na %></td>
  </tr> 
  <tr>
	<th>FedEx Tracking#:</th><td colspan="3"><%=h shipment.fedex_tracking_nr %></td>
  </tr>	
  <tr>
    <th>Comments</th><td colspan="3"><%=h shipment.comments %></td>
  </tr>
</table>
</fieldset>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= form_for(@sample) do |f| %>
  <% @sample.errors.full_messages.each do |msg| %>
    <p>Error: <%= msg %></p>
  <% end %>
  
  <%= render :partial => 'sample_form', :locals => {:f => f, :sample => @sample} %>
  
  <%= raw break_clear %>
  
  <% if @sample.shipment %>
  <div id="ship_ask"> 
  <%= link_to "Edit Shipment Details", '', :onclick => "showHideDiv('ship_ask','ship_edit'); return false;" %>
  </div>
  <% end %>

  <div id="ship_edit", style="display:none">
	<%= f.fields_for :shipment do |s| %>
	  <!--%= s.error_messages %-->
	  <%= render '/shared/errors', model: @sample %>  
      <%= render :partial => 'shipment_form', :locals => {:f => s, :sample => @sample} %>
	<% end %>
  </div>
  
  <%= raw break_clear(f.submit 'Update') %>
<% end %>
  

app/views/samples/index.html.erb
<h1>Listing samples</h1>

<table class="list">
  <tr>
    <th>Barcode</th>
    <th>Sample Name</th>
    <th>Sample Date</th>
    <th>Received Date</th>
    <th>Strain</th>
    <th>Sex</th>
    <th>Age(wks)</th>
    <th>Region</th>
    <th>SC Marker</th>
    <th>FACS Protocol</th>
    <th>SC Marker Validation</th>
    <th>Validation Results</th>
    <th colspan="4"></th>
  </tr>

<% @samples.sort.each do |lab_name, samples| %>
<tr>
  <th colspan="16">Lab: <%=h lab_name %></th>
</tr>
<% samples.each do |sample| %>
  <tr>
    <td><%=link_to sample.barcode_key, sample %></td>
    <td><%=h sample.sample_name %></td>
    <td><%=h sample.sample_date %></td>
    <td><% if sample.shipment %><%=h sample.shipment.date_received %><% end %></td>
    <td><%=h sample.strain %></td>
    <td><%=h sample.sex %></td>
    <td><%=h sample.age_in_weeks %></td>
    <td><%=h sample.intestinal_region %></td>
    <td><%=h sample.intestinal_sc_marker %></td>
    <td><%=h sample.facs_protocol_id %></td>
    <td><%=h sample.sc_marker_validation_method %></td>
    <td><%=h sample.secondary_validation_results %></td>
    
    <% if !sample.shipment && (can? :edit, sample) %>
    <td><%= link_to 'Ship', :action => :sample_ship, :id => sample.id %></td>
    <% else %>
    <td class="ltgrey"><%= (sample.shipment ? (sample.shipment.date_received.nil? ? 'Shipped' : 'Received') : 'Ship') %></td>
    <% end %>   
    <td class="ltgrey">QA</td>      
    <% if can? :edit, sample %>
    <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
    <% else %>
    <td class="ltgrey">Edit</td>
    <% end %>

    <% if can? :delete, sample %>
    <td><%= link_to 'Delete', sample, :confirm => 'Are you sure?', :method => :delete %></td>
    <% else %>
    <td class="ltgrey">Delete</td>
    <% end %>
  </tr>
<% end %>
<% end %>
</table>
<%= link_to 'New sample', new_sample_path %>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/samples/list_intransit.html.erb
<h1>Samples in transit</h1>

<%= form_tag :action => :update_multi do %>
<table class="list">
  <tr>
    <th>Recvd?</th>
    <th>Date Received</th>
    <th>Lab Name</th>
    <th>Barcode</th>
    <th>Sample Name</th>
    <th>Sample Date</th>
    <th>Date Shipped</th>
    <th>FedEx Tracking#</th>
    <th>Shipping Comments</th>
  </tr>

<% @samples.each_with_index do |sample, i| %>
  <% if sample.shipment %>
  <%= fields_for "sample[" + sample.id.to_s + "]", sample do |f| %>
  <% check_box_id   = "sample_" + sample.id.to_s %>
 
  <tr>
    <td><%= check_box_tag(check_box_id) %></td>
						 
    <script type="text/javascript">
    	load_date('<%= check_box_id %>');         
    </script>						  

    <%= f.fields_for :shipment do |s| %>
    <td><!--%=s.calendar_date_select(:date_received, :valid_date_check => "date <= (new Date()).stripTime()", :year_range => [1.years.ago, 0.years.ago], :size => 15)%-->
    <%=s.datepicker 'date_received', dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true, minDate: "-1y", maxDate: "0", size: 15 %>
    </td>
    <td><%=h sample.lab.lab_name %></td>
    <td><%=link_to sample.barcode_key, sample %></td>
    <td><%=h sample.sample_name %></td>
    <td><%=h sample.sample_date %></td>
    <td><%=h sample.shipment.date_shipped %></td>
    <td><%=h sample.shipment.fedex_tracking_nr %></td>
    <td><%=h sample.shipment.comments %></td>
  </tr>
  <% end %>
  <% end %>
<% end %>
<% end %>
</table>
<%= submit_tag 'Update'%>
<% end %>
<%= link_to 'List All', samples_path %>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= form_for @sample, :url => {:action => 'create'} do |f| %>
  <% @sample.errors.full_messages.each do |msg| %>
    <p>Error: <%= msg %></p>
  <% end %>
 
  <%= render :partial => 'sample_form', :locals => {:f => f, :sample => @sample} %>
  
  <%= raw break_clear(f.submit "Save") %>
  
  <%= link_to 'List All', samples_path %>
  
<% end %>
  

app/views/samples/sample_ship.html.erb
<h1>Sample Shipment</h1>
<%= render :partial => 'sample_show', :locals => {:sample => @sample} %>

<%= form_for(@sample, :action => :update) do |f| %>
  
<% f.fields_for :shipment do |s| %>
  <%= render :partial => 'shipment_form', :locals => {:f => s, :sample => @sample} %>
<% end %>
  
<%= raw break_clear(f.submit "Update") %>
<% end %>

app/views/samples/shipment_confirm.html.erb
<br />
<%= render :partial => 'sample_show', :locals => {:sample => @sample} %>

<div id="ship_ask">
<%= link_to "Ship Sample", '', :onclick => "showHideDiv('ship_ask','ship_samples'); return false;" %> | 
<%= link_to 'Edit sample', edit_sample_path(@sample) %>
</div>

<div id="ship_samples", style="display:none">
  <%= form_for(@sample, :action => :update) do |f| %>
  
  <%= f.fields_for :shipment do |s| %>
    <%= render :partial => 'shipment_form', :locals => {:f => s, :sample => @sample} %>
  <% end %>
  <%= raw break_clear %> 
  <%= f.submit "Update" %>
  <% end %>
</div>

app/views/samples/show.html.erb
<h1>Show Samples</h1>

<%= render :partial => 'sample_show', :locals => {:sample => @sample} %>
<% if @sample.shipment %>
<%= render :partial => 'shipment_show', :locals => {:shipment => @sample.shipment} %>
<% end %>
<%= raw break_clear %>
<% if can? :new, Sample %><%= link_to 'New sample', new_sample_path %> | <% end %>
<% if can? :edit, @sample %>
<%= link_to 'Edit', edit_sample_path(@sample) %> | 
<% end %>
<%= link_to 'List All', samples_path %>