config/routes.rb
ISCCLims::Application.routes.draw do
  
  root :to => 'welcome#index'
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :sessions
  resources :auth_users
  resources :users
  match 'forgot' => 'users#forgot', :as => :forgot
  match 'activate/:activation_code' => 'users#activate', :as => :activate
  match 'reset/:reset_code' => 'users#reset', :as => :reset

  get 'samples/autocomplete_sample_strain'  
  get 'samples/autocomplete_sample_intestinal_sc_marker'
  get 'samples/autocomplete_sample_sc_marker_validation_method'
  resources :samples do
    collection do
      get :shipment_confirm
      get :sample_ship
    end    
  end
  
  match 'list_intransit' => 'samples#list_intransit', :as => :recv_samples
  match 'show_sop' => 'samples#show_sop', :as => :show_sop
  match 'sample_results' => 'samples#show_results', :as => :sample_results
  
  resources :result_files
  match 'show_rdef' => 'result_files#show_rdef', :as => :show_rdef
  match 'choose_lab' => 'result_files#choose_lab', :as => :choose_lab
  match 'edit_multi' => 'result_files#edit_multi', :as => :edit_multi
  match 'update_multi' => 'result_files#update_multi', :as => :update_multi
  match 'destroy' => 'result_files#destroy', :as => :destroy
  match '/:controller(/:action(/:id))'
  

end

app/models/auth_user.rb
# == Schema Information
#
# Table name: auth_users
#
#  id         :integer(2)      not null, primary key
#  lab_id     :integer(2)      not null
#  name       :string(50)      default(""), not null
#  email      :string(75)      default(""), not null
#  notes      :string(255)
#  created_at :datetime        not null
#  updated_at :timestamp
#

class AuthUser < ActiveRecord::Base
  include Authentication
  
  belongs_to :lab
  has_one :user
  
  validates_presence_of     :lab_id, :email, :name
  
  validates_length_of       :email,    :within => 6..100 #r@a.wk
  validates_uniqueness_of   :email
  validates_format_of       :email,    :with => Authentication.email_regex, :message => Authentication.bad_email_message

end

app/controllers/auth_users_controller.rb
class AuthUsersController < ApplicationController
  load_and_authorize_resource
  
  before_filter :dropdowns, :only => [:new, :edit]
  
  # GET /auth_users
  # GET /auth_users.xml
  def index
    @auth_users = AuthUser.includes(:lab).order('labs.lab_name, auth_users.name').all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @auth_users }
    end
  end

  # GET /auth_users/1
  # GET /auth_users/1.xml
  def show
    @auth_user = AuthUser.includes(:lab).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @auth_user }
    end
  end

  # GET /auth_users/new
  # GET /auth_users/new.xml
  def new
    @auth_user = AuthUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @auth_user }
    end
  end

  # GET /auth_users/1/edit
  def edit
    @auth_user = AuthUser.includes(:user).find(params[:id])
  end

  # POST /auth_users
  # POST /auth_users.xml
  def create
    @auth_user = AuthUser.new(params[:auth_user])

    respond_to do |format|
      if @auth_user.save
        flash[:notice] = 'Authorized user was successfully created.'
        format.html { redirect_to(@auth_user) }
        format.xml  { render :xml => @auth_user, :status => :created, :location => @auth_user }
      else
        dropdowns
        format.html { render :action => "new" }
        format.xml  { render :xml => @auth_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /auth_users/1
  # PUT /auth_users/1.xml
  def update
    @auth_user = AuthUser.find(params[:id])

    respond_to do |format|
      if @auth_user.update_attributes(params[:auth_user])
        flash[:notice] = 'Authorized user was successfully updated.'
        format.html { redirect_to(@auth_user) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @auth_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /auth_users/1
  # DELETE /auth_users/1.xml
  def destroy
    @auth_user = AuthUser.find(params[:id])
    @auth_user.destroy

    respond_to do |format|
      format.html { redirect_to(auth_users_url) }
      format.xml  { head :ok }
    end
  end
  
protected
  def dropdowns
    @labs = Lab.order(:lab_name).all
  end
end

app/views/auth_users/_auth_user.html.erb
<fieldset class="form">
<legend>User Info</legend>
<table class="form">
  	<tr>
	  <th><%= f.label :lab_id, 'Lab' %></th>
      <td><%= f.collection_select(:lab_id, @labs, :id, :lab_name, {:include_blank => 'Select..'}) %></td>
	</tr>
	
	<tr>
  	  <th><%= f.label :name %></th>
	  <td><%= f.text_field :name %></td>
	</tr>
	
	<tr>
	  <th><%= f.label :email %></th>
      <td><%= f.text_field :email %></td>
	</tr>
	
    <tr>
	  <th><%= f.label :notes %></th>
      <td><%= f.text_field :notes %></td>
	</tr>
</table>
</fieldset>
<%= raw break_clear %>

app/views/auth_users/edit.html.erb
<h1>Editing Authorized User</h1>

<%= form_for(@auth_user) do |f| %>
  
  <% @auth_user.errors.full_messages.each do |msg| %>
    <p>Error: <%= msg %></p>
  <% end %>

  <%= render :partial => 'auth_user', :locals => {:f => f} %>
  
  <%= f.submit "Update" %>
<% end %>

<%= link_to 'Back', auth_users_path %>

app/views/auth_users/index.html.erb
<h1>List Authorized User</h1>

<table class="list">
  <tr>
  	<th>Lab Name</th>
    <th>User name</th>
	<th>Email</th>
	<th>Created on</th>
    <th colspan="2"></th>
  </tr>

  <% @auth_users.each do |auth_user| %>
  <tr>
  	<td><%=h auth_user.lab.lab_name %></td>
    <td><%=h auth_user.name %></td>
	<td><%=h auth_user.email %></td>
	<td><%=h format_datetime(auth_user.created_at) %></td>
    <td><%= link_to 'Edit', edit_auth_user_path(auth_user) %></td>
    <td><%= link_to 'Delete', auth_user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Auth User', new_auth_user_path %>

app/views/auth_users/new.html.erb
<h1>New Authorized User</h1>

<%= form_for(@auth_user) do |f| %>
  <% @auth_user.errors.full_messages.each do |msg| %>
    <p>Error: <%= msg %></p>
  <% end %>

  <%= render :partial => 'auth_user', :locals => {:f => f} %>
  
  <%= f.submit "Create" %>
<% end %>

<%= link_to 'List All', auth_users_path %>

app/views/auth_users/show.html.erb
<h1>Show Authorized User</h1>
<fieldset class="info">
<legend>User Info</legend>
<table class="info">
  	<tr>
  	  <th>Lab name:</th>
	  <td><%=h @auth_user.lab.lab_name %></td>
	</tr>
	
	<tr>
	  <th>User name:</th>
      <td><%=h @auth_user.name %></td>
	</tr>
    
	<tr>
	  <th>Email: </th>
      <td><%=h @auth_user.email %></td>
	</tr>
	
	<tr>
	  <th>Notes: </th>
      <td><%=h @auth_user.notes %></td>
	</tr>
	
	<tr>
	  <th>User login:</th>
      <td><%=h (@auth_user.user ? @auth_user.user.login : 'N/A') %></td>
	</tr>
  </table>
</fieldset>
<%= raw break_clear %>
<%= link_to 'New Auth User', new_auth_user_path %> |
<%= link_to 'Edit', edit_auth_user_path(@auth_user) %> |
<%= link_to 'List All', auth_users_path %>