config/routes.rb
ISCCLims::Application.routes.draw do
  
  root :to => 'welcome#index'
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :sessions
  resources :auth_users
  resources :users
  match 'forgot' => 'users#forgot', :as => :forgot
  match 'activate/:activation_code' => 'users#activate', :as => :activate
  match 'reset/:reset_code' => 'users#reset', :as => :reset

  get 'samples/autocomplete_sample_strain'  
  get 'samples/autocomplete_sample_intestinal_sc_marker'
  get 'samples/autocomplete_sample_sc_marker_validation_method'
  resources :samples do
    collection do
      get :shipment_confirm
      get :sample_ship
    end    
  end
  
  match 'list_intransit' => 'samples#list_intransit', :as => :recv_samples
  match 'show_sop' => 'samples#show_sop', :as => :show_sop
  match 'sample_results' => 'samples#show_results', :as => :sample_results
  
  resources :result_files
  match 'show_rdef' => 'result_files#show_rdef', :as => :show_rdef
  match 'choose_lab' => 'result_files#choose_lab', :as => :choose_lab
  match 'edit_multi' => 'result_files#edit_multi', :as => :edit_multi
  match 'update_multi' => 'result_files#update_multi', :as => :update_multi
  match 'destroy' => 'result_files#destroy', :as => :destroy
  match '/:controller(/:action(/:id))'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                        :integer(4)      not null, primary key
#  login                     :string(25)      default(""), not null
#  lab_id                    :integer(4)      not null
#  auth_user_id              :integer(4)
#  email                     :string(255)
#  role                      :string(10)
#  crypted_password          :string(40)
#  salt                      :string(40)
#  activation_code           :string(50)
#  activated_at              :datetime
#  reset_code                :string(50)
#  updated_at                :datetime
#  remember_token            :string(255)
#  remember_token_expires_at :datetime
#

require 'digest/sha1'

class User < ActiveRecord::Base
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  
  belongs_to :lab
  belongs_to :auth_user
  
  def before_validation_on_create
    auth_user = AuthUser.find_by_email(email) if email
    self.auth_user_id = auth_user.id if auth_user
  end
  
  validates_presence_of     :lab_id
  validates_associated      :lab
  
  validates_presence_of     :auth_user_id, :message => "email address not authorized - please contact your PI"
  validates_associated      :auth_user

  validates_presence_of     :login
  validates_length_of       :login,    :within => 3..40
  validates_uniqueness_of   :login
#  validates_format_of       :login,    :with => Authentication.login_regex, :message => Authentication.bad_login_message

  #validates_format_of       :name,     :with => Authentication.name_regex,  :message => Authentication.bad_name_message, :allow_nil => true
  #validates_length_of       :name,     :maximum => 100

  validates_presence_of     :email
  validates_length_of       :email,    :within => 6..100 #r@a.wk
  validates_uniqueness_of   :email
#  validates_format_of       :email,    :with => Authentication.email_regex, :message => Authentication.bad_email_message

  before_create :make_activation_code 
  
  # Class virtual attribute for current_user (set in application controller)
  cattr_accessor :current_user
  
  attr_accessible :lab_id, :login, :email, :password, :password_confirmation
  
  def has_admin_access?
    (role == 'admin' && lab_id == Lab::STANFORD_LAB_ID)
    #lab_id == Lab::STANFORD_LAB_ID
  end
  
  def has_consortium_access?
    #(role == 'admin' && [Lab::STANFORD_LAB_ID, Lab::PRINCETON_LAB_ID].include?(lab_id) ? true : false)
    true
  end

  # Activates the user in the database.
  def activate!
    @activated = true
    self.activated_at = Time.now.utc
    self.activation_code = nil
    save(:validate => false)
  end
  
  # Returns true if the user has just been activated.
  def recently_activated?
    @activated
  end

  def active?
    # the existence of an activation code means they have not activated yet
    activation_code.nil?
  end
  
  def reset!
    @reset = true
    create_reset_code
  end  
  
  # Returns true if the user has just requested a password reset
  def recently_reset?
    @reset
  end
  
  def delete_reset_code
    self.reset_code = nil
    save(:validate => false)
  end

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(lab_id, login, password)
    return nil if login.blank? || password.blank?
    u = self.where('login = ? AND lab_id = ? AND activated_at IS NOT NULL', login, lab_id).first  # need to get the salt
	  #u = find_by_login(login)
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end

protected
  def make_activation_code
    self.activation_code = self.class.make_token
  end
  
  def create_reset_code
    self.reset_code = self.class.make_token
    save(:validate => false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  
  skip_before_filter :login_required, :only => [:new, :create, :activate, :forgot, :reset]
  
  def index
    authorize! :read, User
    @users = User.includes(:lab, :auth_user).order('lab_id, login').all
  end
  
  # render new.rhtml
  def new
    @user = User.new
    @labs = Lab.order(:lab_name).all
  end
 
  def create
    logout_keeping_session!
    @user = User.new(params[:user])
    success = @user && @user.save
    if success && @user.errors.empty?
      redirect_back_or_default('/')
      flash[:notice] = "Thanks for signing up!  We're sending you an email with your activation code."
    else
      flash[:error]  = "We couldn't set up that account, sorry.  Please try again, or contact system admin"
      @labs = Lab.order(:lab_name).all
      render :action => 'new'
    end
  end
  
  # render edit.html
  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end
  
  def update
    @user = User.find(params[:id])
    authorize! :update, @user
         
    if @user.authenticated?(params[:curr_user][:current_password])
      if @user.update_attributes(params[:user])
        flash[:notice] = "User has been updated"
        redirect_to users_url
      else
        flash.now[:error] = "Error updating user"
        render :action => 'edit'
      end
      
    else
      flash.now[:error] = "Incorrect current password entered - please try again"
      render :action => 'edit'
    end
  end

  def activate
    logout_keeping_session!
    user = User.find_by_activation_code(params[:activation_code]) unless params[:activation_code].blank?
    case
    when (!params[:activation_code].blank?) && user && !user.active?
      user.activate!
      flash[:notice] = "Signup complete! Please sign in to continue."
      redirect_to '/login'
    when params[:activation_code].blank?
      flash[:error] = "The activation code was missing.  Please follow the URL from your email."
      redirect_to '/login'
    else 
      flash[:error]  = "We couldn't find a user with that activation code -- check your email? Or maybe you've already activated -- try signing in."
      redirect_to '/login'
    end
  end
  
  def forgot
    if request.post?
      user = User.find_by_email(params[:user][:email])
      
      if user
        user.reset!
        flash[:notice] = "Reset code sent to #{user.email}"
        redirect_to login_path
      else
        flash[:error] = "#{params[:user][:email]} does not exist in system"
        redirect_to forgot_path
      end
    end
  end
  
  def reset
    @user = User.find_by_reset_code(params[:reset_code]) unless params[:reset_code].nil?
    
    if request.post? # Processing reset of password
      if @user.update_attributes(:password => params[:user][:password],
                                 :password_confirmation => params[:user][:password_confirmation])
        self.current_user = @user
        @user.delete_reset_code
        flash[:notice] = "Password reset successfully for #{@user.email}"
        redirect_to :controller => 'welcome', :action => 'index'
      else
        render :action => :reset # Error saving new password, should result in validation error message
      end
      
    else             # Requesting form for entry of new password
      if !@user.nil?
        render :action => :reset
      else
        flash[:error]  = "We couldn't find a user with that reset code -- check your email? Or maybe you've already reset -- try signing in."
        redirect_to '/login'
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    authorize! :destroy, @user
    
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/users/_user_bar.html.erb
<% if logged_in? -%>
  <div id="user-bar-greeting">Logged in as <%= link_to_current_user :content_method => :login %></div>
  <div id="user-bar-action"  >(<%= link_to "Log out", logout_path, { :title => "Log out" }    %>)</div>
<% else -%>
  <div id="user-bar-greeting"><%= link_to_login_with_IP 'Not logged in', :style => 'border: none;' %></div>
  <div id="user-bar-action"  ><%= link_to "Log in",  login_path,  { :title => "Log in" } %> /
                               <%= link_to "Sign up", signup_path, { :title => "Create an account" } %></div>
<% end -%>

app/views/users/edit.html.erb
<br />
<%= render '/shared/errors', model: @user %>
<!--%= error_messages_for :user %-->

<%= form_for(@user) do |f| -%>
<fieldset class="form">
<legend>Lab: <%=h @user.lab.lab_name %></legend>
<table class="form">
<tr>
	<th><%= f.label :login %></th>
	<td><%= f.text_field :login %></td>
</tr>
<tr>
    <th><%= f.label :email %></th>
    <td><%= f.text_field :email %></td>
</tr>
<tr>
    <th><%= label :curr_user, :current_password %></th>
    <td><%= password_field :curr_user, :current_password %></td>
</tr>
<tr>
    <th><%= f.label :new_password %></th>
    <td><%= f.password_field :password %></td>
</tr>
<tr>
    <th><%= f.label :new_password_confirmation %></th>
    <td><%= f.password_field :password_confirmation %></td>
</tr>
</table>
</fieldset>

<%= raw break_clear(f.submit 'Update') %>

<% end -%>

app/views/users/forgot.html.erb
<h1>Reset password request</h1>

<%= form_for :user do |f| -%>

<p><%= f.label :email %><br/>
<%= f.text_field :email %></p>

<p> <%=link_to 'Cancel', login_path %>
        <%= submit_tag 'Submit' %></p>
<% end -%>


<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/users/index.html.erb
<h1>List Users</h1>

<table class="list">
  <tr>
  	<th>Lab Name</th>
    <th>User name</th>
	<th>Login</th>
	<th>Email</th>
	<th>Activated on</th>
    <th colspan="2"></th>
  </tr>

  <% @users.each do |user| %>
  <tr>
  	<td><%=h (user.lab ? user.lab.lab_name : 'N/A') %></td>
    <td><%=h (user.auth_user ? user.auth_user.name : 'N/A') %></td>
	<td><%=h user.login %></td>
	<td><%=h user.email %></td>
	<td><%=h format_datetime(user.activated_at) %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Delete', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>Sign up as a new user</h1>
<% @user.password = @user.password_confirmation = nil %>

<%= render '/shared/errors', model: @user %>

<%= form_for :user, :url => users_path do |f| -%>
<p><%= f.label :lab %><br/>
<%= f.collection_select(:lab_id, @labs, :id, :lab_name, {:include_blank => 'Select Lab'}) %></p>

<p><%= f.label :login %><br/>
<%= f.text_field :login %></p>

<p><%= f.label :email %><br/>
<%= f.text_field :email %></p>

<p><%= f.label :password %><br/>
<%= f.password_field :password %></p>

<p><%= f.label :password_confirmation, 'Confirm Password' %><br/>
<%= f.password_field :password_confirmation %></p>

<p><%= submit_tag 'Sign up' %></p>
<% end -%>

app/views/users/reset.html.erb
<%= render '/shared/errors', model: @user %>

<%= form_for :user do |f| -%>
  <table id="newedit">
  	 <thead>
        <tr>
          <th colspan="2" >Pick a new password for <%= @user.email %></th>
        </tr>
     </thead>
	 
	 <tbody>
	 	<tr>
	      <td align="right"><label>Password:</label></td>
		  <td><%= f.password_field :password %></td>
        </tr>
		<tr>
		  <td align="right"><label>Confirm Password:</label></td>
		  <td><%= f.password_field :password_confirmation %></td>
		</tr>
		<tr>
		  <td></td>
		  <td><%= submit_tag 'Reset' %></td>
        </tr>
     </tbody>
  </table>
<% end -%>